CREATE TABLE `suivi_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`prestataire` varchar(200),
	`ut` varchar(50),
	`bat` varchar(50),
	`intitule` text,
	`numDevis` varchar(100),
	`dateDevis` varchar(50),
	`montant` decimal(12,2),
	`validationKnitiv` varchar(200),
	`numConnectImmo` varchar(100),
	`numDA` varchar(100),
	`numCDA` varchar(100),
	`pv` varchar(100),
	`numReception` varchar(100),
	`numAT` varchar(100),
	`axeLocal` varchar(100),
	`axeCentral` varchar(100),
	`dateDacia` varchar(50),
	`clotureAT` varchar(50),
	`commentaires` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suivi_entries_id` PRIMARY KEY(`id`)
);
