CREATE TABLE `deliverables` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20) NOT NULL,
	`mission` varchar(20) NOT NULL,
	`category` varchar(200) NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`contractualDelay` varchar(500) NOT NULL,
	`referenceDate` bigint,
	`dueDate` bigint,
	`deliveredDate` bigint,
	`status` enum('a_venir','en_cours','livre','en_retard','non_applicable') NOT NULL DEFAULT 'a_venir',
	`responsable` varchar(200),
	`notes` text,
	`alertDaysBefore` int DEFAULT 7,
	`alertSent` int NOT NULL DEFAULT 0,
	`priority` enum('haute','moyenne','basse') NOT NULL DEFAULT 'moyenne',
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deliverables_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `suivi_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`prestataire` varchar(200),
	`ut` varchar(50),
	`bat` varchar(50),
	`intitule` text,
	`numDevis` varchar(100),
	`dateDevis` varchar(50),
	`montant` varchar(50),
	`validationKnitiv` varchar(200),
	`numConnectImmo` varchar(100),
	`numDA` varchar(100),
	`numCDA` varchar(100),
	`pv` varchar(100),
	`numReception` varchar(100),
	`numAT` varchar(100),
	`axeLocal` varchar(100),
	`axeCentral` varchar(100),
	`dateDacia` varchar(50),
	`clotureAT` varchar(100),
	`commentaires` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suivi_entries_id` PRIMARY KEY(`id`)
);
